- name: Configuring MySQL DB
  hosts: web
  become: yes

  tasks:
  - name: installing MYSQL
    ansible.builtin.dnf:
      name: mysql-server
      state: latest

  - name: Start and Enable MySQL server
    ansible.builtin.service:
      name: mysqld
      state: started
      enabled: yes

  - name: install python mysql dependencies
    ansible.builtin.pip:
      name:
      - PyMySQL
      - cryptography
      executable: pip3.9 # pip3.11 if python version is 3.11

# check whether password setup is done or not
  - name: check DB Connection
    community.mysql.mysql_info:
      login_user: root
      login_password: ExpensceApp@321
      login_host: ansible.rajasekhar.online
      filter: version
     # register: mysql_info

  - name: print mysql info
    ansible.builtin.debug:
      msg: "Output is : {{ mysql_info}}"

  - name: Setting up MySQL root password
    ansible.builtin.command: mysql_secure_installation --set-root-pass ExpenseApp@1