- name: Configuring MySQL DB
  hosts: web
  become: yes

  tasks:
  - name: installing MYSQL
    ansible.builtin.dnf:
      name: mysql
      state: latest

  - name: Enabling MySQL
    ansible.builtin.service:
      name: mysqld
      state: enabled

  - name: Starting MySQL
    ansible.builtin.service:
      name: mysql
      state: start

  - name: Setting up MySQL root password
    ansible.builtin.command: mysql_secure_installation --set-root-pass ExpenseApp@1